Feature/ros2
AkariGroup/docs pull request #133
Opened 2023-10-06 13:58 UTC by kazyam53

ROS2のセットアップ、サンプル、通信仕様の説明を追加しました。
内容確認ください。

2023-10-07 09:23 UTC, kazyam53 commented
画像追加しました。

2023-10-08 13:24 UTC, mantues requested changes
コマンド一部修正をお願いします。

2023-10-09 06:44 UTC, kazyam53 commented on source/ros2/example.rst
> +    ros2 run akari_client_example m5_subscriber set_pinout
雑コピーですね…直しました。

2023-10-09 06:45 UTC, kazyam53 commented on source/ros2/example.rst
> +    ros2 run akari_client_example m5_subscriber reset_m5
こちらも直しました。

2023-10-09 06:45 UTC, kazyam53 commented
@mantues 
直しました…ありがとうございます！

2023-10-10 21:43 UTC, mantues approved these changes
問題ないと思います

2023-10-14 22:15 UTC, merged