Add local training
AkariGroup/docs pull request #143
Opened 2024-01-18 10:53 UTC by kazyam53

YOLOの学習をローカルPCで実行する方法を追加しました。

2024-01-26 00:33 UTC, Wisteria720 requested changes
1点、修正お願いします。

2024-01-26 05:24 UTC, kazyam53 commented on source/dev/custom_object_detection/training.rst
> +`5. `train フォルダの中に、:doc:`annotation` で準備した画像ファイル(.jpg)とアノテーションファイル(.txt)、識別する物体のクラス情報が入った `class.txt` を全部入れます。画像もアノテーションファイルもラベルごとにフォルダ分けせず、train直下にまとめて置きます。
ありがとうございます。修正しました。

2024-01-26 05:24 UTC, kazyam53 commented
@Wisteria720 
修正しました。確認お願いします！

2024-01-28 23:14 UTC, Wisteria720 approved these changes
修正ありがとうございます！

2024-01-29 12:40 UTC, merged