Feature/light ver
AkariGroup/docs pull request #180
Opened 2024-12-11 13:07 UTC by kazyam53

light版のドキュメント更新です。
light版のソフト、ハードリリース後にマージします。

2024-12-11 23:39 UTC, Wisteria720 requested changes
一部画像抜けとURL不備があります
対応していいですか？

2024-12-11 23:39 UTC, Wisteria720 commented on source/assembly_light/setup_soft/setup_ansible.rst
> +.. image:: ../../images/assembly_light/setup_soft/boot_01.jpg
画像データが入っていない

2024-12-11 23:39 UTC, Wisteria720 commented on source/assembly_light/setup_soft/setup_feetech.rst
> +.. image:: ../../images/assembly_light/setup_feetech/feetech_02.jpg
画像データが入っていない

2024-12-11 23:39 UTC, Wisteria720 commented on source/spec/hard_spec_light.rst
> +https://m5stack-store.myshopify.com/collections/m5-core/products/grey-development-core
URLがGrayのものになっている

2024-12-11 23:39 UTC, Wisteria720 commented on source/spec/hard_spec_light.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ラズパイの情報が入っていませんが、このままリリースで大丈夫ですか？

2024-12-11 23:41 UTC, kazyam53 commented
@Wisteria720 
そう言われるとあとでやろうと思ってそのままになってるのが結構あります…ダメですね。
出来る範囲で対応いただけるととてもありがたいです。特に画像の辺り。

2024-12-12 10:20 UTC, Wisteria720 commented
@kazyam53 
画像追加しました
仕様については別ブランチ切ってプルリク出しています[https://github.com/AkariGroup/docs/pull/181](https://github.com/AkariGroup/docs/pull/181)

2024-12-19 04:05 UTC, kazyam53 commented
Lightの概要を追記しました。
@Wisteria720 
リリースしたいので、再レビューをお願いします！

2024-12-19 11:28 UTC, Wisteria720 approved these changes
LGTM!

2024-12-19 22:11 UTC, merged